Add java language
spencermwoo/randomness-in-programming-languages pull request #8
Opened 2021-09-23 15:17 UTC by satyamsettyeswara

Add the Random program in source directory

2021-09-23 18:30 UTC, SpencerWoo requested changes
@satyamsettyeswara Amazing!  Thanks for this PR and following all the guidelines.  

Everything looks perfect except I'd like some refactoring on the java code.  All the functionality is there, just like it to be more consistent and clean.  I've left some comments.

I'll give it a few days in case you want to make those changes yourself (feel free to add commits to your current branch or rebase) -- otherwise I'm okay with merging it as-is and then I can make some SF/refactoring changes.

TLDR;
* Make requested changes
* If no changes are made, I'll merge as-is in a few days because it's a great PR and I can make the changes myself later

Let me know if there's any questions.  Otherwise thanks for contributing!  Hope to see another PR for another language =)

2021-09-23 18:30 UTC, SpencerWoo commented on sources/Java.java
> +		int range = Integer.parseInt(args[0]);
We can add error handling to gracefully fail here or even ask of inputs

2021-09-23 18:30 UTC, SpencerWoo commented on sources/Java.java
> +		int start_time = (int) System.currentTimeMillis();
Why are we avoiding using the native `long`?  Generally, I'd like to remove all type casting.

2021-09-23 18:30 UTC, SpencerWoo commented on sources/Java.java
> +			frequency[r_number] +=1;
Source formatting to be consistent.  In some places we have spaces after `=` or `)`.

2021-09-23 18:30 UTC, SpencerWoo commented on sources/Java.java
> +		String filename = System.getProperty("user.dir")+"\\outputs\\"+"java_"+numbers+"_"+trails+".txt";
We should use `String.format` instead of concatenating strings with `+`.

2021-09-23 18:30 UTC, SpencerWoo commented on sources/Java.java
> +			BufferedWriter writer = new BufferedWriter(new FileWriter(filename));
I think we can write with `FileWriter` alone (without `BufferedWriter`)?  Let me know

2021-09-23 18:35 UTC, SpencerWoo commented
Can you also update the `sources/README.md` to move `Java` from Future to Completed language? 
 https://github.com/spencermwoo/randomness-in-programming-languages/pull/1/files#diff-a638ced7ac6ffb78c9770b5daef75b2e7749fed18298b0c2ec4df6a02002b05a

2021-09-24 05:22 UTC, satyamsettyeswara commented
Added the requested changes. Tell me if you want any changes in the java code

2021-09-24 21:55 UTC, spencermwoo approved these changes
Thanks for making those changes.  This looks great.  I've left a few minor notes but I'll merge later in the week.

2021-09-24 21:55 UTC, spencermwoo commented on sources/Java.java
> +		int trails = 0;
Let's rename this variable to `trials`

2021-09-24 21:55 UTC, spencermwoo commented on sources/Java.java
> +				probability[i] = frequency[i] / (double) trails;
`frequency[]` can be type `double` to avoid type-casting here

2021-09-24 21:55 UTC, spencermwoo commented on sources/Java.java
> +		for (long i = 0; i < trails; i++) {
We aren't using `i` but it's best to keep it as `int`

2021-09-24 21:57 UTC, spencermwoo commented on sources/Java.java
> +		System.out.println(String.format("--- %f seconds ---", (duration * 0.001)));
We can also add newlines to separate the sections to help readability.

Typically that would be done with functions, but I enjoy one master function for this type of program.

2021-09-25 09:08 UTC, satyamsettyeswara commented
Added all the requested changes

2021-09-25 18:41 UTC, merged

2021-09-25 18:46 UTC, SpencerWoo commented
Thanks a ton @satyamsettyeswara - I've merged your pull request into master!